version: '2'
services:
  eventmanager-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/eventmanager/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=eventmanager
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
